WIP: Stop sniffing mimetype on playlists and don't use playlist.once anymore
radiorabe/klangbecken pull request #48
Opened 2020-05-01 10:15 UTC by hairmare

This replaces the mime type sniffing that we are doing when loading a playlist with a hardcoded mime type. We can always assume that the generated m3u files have a `text/plain` mime type. With this assumption liquidsoap won't log `Wrong mime type application/octet-stream for playlist!` if the file is empty.

We need to switch to not using `playlist.once` anymore since it is deprecated nowadays: https://github.com/savonet/liquidsoap/pull/1015. I think we don't need to use `reload_mode="once"` but can stick to `reload_mode=watch` since the prio file is handled in a way that watching it leads to the behaviour we want.

* [x] deactivate mime type sniffing
* [x] refactor so we don't use `playlist.once anymore`
* [ ] test if this works with all the liquidsoap versions we are supporting (currently 1.3.2 with the possibilty to upgrade to 1.3.7 which has already been built, 1.4 support depends on us rolling out CentOS 8)

2020-05-01 15:10 UTC, spameier commented
Maybe we should use `application/x-mpegURL`.
I just noticed the following lines in the logs:
```
2020/05/01 17:05:43 [classics:3] Playlist treated as format application/x-mpegURL
```
Not entirely sure though. :confused:

2020-05-01 20:54 UTC, hairmare commented
> Maybe we should use `application/x-mpegURL`.

I changed it to `audio/x-mpegurl` after referencing the [docs](https://www.liquidsoap.info/doc-1.3.2/playlist_parsers.html).

2020-08-20 11:23 UTC, smlz requested changes
What is the reason for removing `.once` for the prio playlist?

The rest looks good.

2020-08-20 11:23 UTC, smlz commented on klangbecken.liq
> -prio = playlist.once(id="prio", reload_mode="watch", path.concat(DATA_DIR, "prio.m3u"))
You should leave the `.once`, to double ensure that the prio playlist never loops.

2021-01-13 22:39 UTC, smlz commented
I think we can close this one. Right?

2021-04-05 10:47 UTC, hairmare commented
> I think we can close this one. Right?

At a glance, I don't think so... IMO we should still circumvent mimetype sniffing and get rid of `playlist.once`.

2021-04-13 18:31 UTC, smlz commented
`playlist.once` is gone in the new code.

As far as mime type sniffing goes, I tried this out some time ago with strange results. Manually setting the mime type makes `check_next` _always_ fail, and thus sends the player into an endless loop. :cold_sweat:

2021-04-13 20:46 UTC, closed without merging